### ISSUE TITLE
Add unit test 

### ISSUE THREAD

**Issue by okram999** [RocketScienceProjects/BlueKing#1]
@arunpsg can you try to add a unit test to the code?

**Comment by arunpsg** [comment]
@okram999 Yeah I'll do it. Can i do it this weekend?.

**Comment by okram999** [comment]
@arunpsg Thanks!  trying to use surefire from maven, once that is in place

**Comment by arunpsg** [comment]
@okram999 Done!. Check it out!

**Comment by okram999** [comment]
Awesome, let me take a look tommorow and will update it back. @arunpsg .. Then we should reconnect

**Comment by okram999** [comment]
Done with the test execution via the jenkins. Had to update the pom.xml for the test case directory. @arunpsg
